spring:
  application:
    name: graphql-demo
  datasource:
    url: jdbc:h2:mem:graphql-db
    username: SA
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 9001